
development:
  adapter: postgresql
  encoding: unicode
  database: project_defined_development
  username: DanielBushkanets
  pool: 5
  password: danbush123

test:
  adapter: postgresql
  encoding: unicode
  database: project_defined_test
  username: DanielBushkanets
  pool: 5
  password: danbush123

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>