
development:
  adapter: postgresql
  encoding: unicode
  database: project_defined_development
  username: DanielBushkanets
  pool: 5
  password: danbush123

test:
  adapter: postgresql
  encoding: unicode
  database: project_defined_test
  username: DanielBushkanets
  pool: 5
  password: danbush123

