
development:
  adapter: postgresql
  encoding: unicode
  database: project_defined_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: project_defined_test
  pool: 5
  password:

